name: ci

on :
  push:
  
env:
  sln: VO.Templates.sln

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.sln}}
    - name: Build
      run: dotnet build ${{env.sln}} --no-restore
    - name: Test
      run: dotnet test ${{env.sln}} --no-build --verbosity normal
    - name: Publish to Nuget 
      run: dotnet nuget push "**/src/nuget/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -n 
